server {
    listen 80;
    server_name aikey.today www.aikey.today;
    root /usr/share/nginx/html;
    index index.html;

    # # SPA 라우팅: 파일이 없으면 index.html로 폴백
    # location / {
    #     try_files $uri $uri/ /index.html;
    # }
    location / {
        proxy_pass http://127.0.0.1:6075;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 정적 자산 캐싱
    location ~* \.(js|css|woff|woff2|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /api/ {
        proxy_pass http://fastapi_server:8100/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /media/ {
        proxy_pass http://fastapi_server:8100/media/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
