import React from 'react'
import List from 'src/shared/layout/list/List.tsx'
import ListContent from 'src/shared/layout/list/ListContent.tsx'
import Badge from 'src/features/badges/components/Badge.tsx'

const Badges = () => {
    return (
        <div className="flex min-h-screen w-full items-center justify-center">
            <List>
                <ListContent title="With Border">
                    <Badge text="Badge" textSize="xs" />
                    <Badge
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="With Border And Dot">
                    <Badge
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="red"
                    />
                    <Badge
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="yellow"
                    />
                    <Badge
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="green"
                    />
                    <Badge
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="blue"
                    />
                    <Badge
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="indigo"
                    />
                    <Badge
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="purple"
                    />
                    <Badge
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Pill With Border">
                    <Badge shape="pill" text="Badge" textSize="xs" />
                    <Badge
                        shape="pill"
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="Pill With Border And Dot">
                    <Badge
                        shape="pill"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="With Border And Remove Button">
                    <Badge add="button" text="Badge" textSize="xs" />
                    <Badge
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textColor="red"
                        textSize="xs"
                        addedColor="red"
                    />
                    <Badge
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textColor="yellow"
                        textSize="xs"
                        addedColor="yellow"
                    />
                    <Badge
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textColor="green"
                        textSize="xs"
                        addedColor="green"
                    />
                    <Badge
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textColor="blue"
                        textSize="xs"
                        addedColor="blue"
                    />
                    <Badge
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textColor="indigo"
                        textSize="xs"
                        addedColor="indigo"
                    />
                    <Badge
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textColor="purple"
                        textSize="xs"
                        addedColor="purple"
                    />
                    <Badge
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textColor="pink"
                        textSize="xs"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Pill With Border And Remove Button">
                    <Badge
                        shape="pill"
                        add="button"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Flat">
                    <Badge type="flat" text="Badge" textSize="xs" />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="Flat Pill">
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="Flat With Dot">
                    <Badge type="flat" text="Badge" add="dot" textSize="xs" />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="red"
                        add="dot"
                        textColor="red"
                        textSize="xs"
                        addedColor="red"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="yellow"
                        add="dot"
                        textColor="yellow"
                        textSize="xs"
                        addedColor="yellow"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="green"
                        add="dot"
                        textColor="green"
                        textSize="xs"
                        addedColor="green"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="blue"
                        add="dot"
                        textColor="blue"
                        textSize="xs"
                        addedColor="blue"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="indigo"
                        add="dot"
                        textColor="indigo"
                        textSize="xs"
                        addedColor="indigo"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="purple"
                        add="dot"
                        textColor="purple"
                        textSize="xs"
                        addedColor="purple"
                    />
                    <Badge
                        type="flat"
                        text="Badge"
                        badgeColor="pink"
                        add="dot"
                        textColor="pink"
                        textSize="xs"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Flat Pill With Dot">
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        add="dot"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="red"
                        add="dot"
                        textColor="red"
                        textSize="xs"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="yellow"
                        add="dot"
                        textColor="yellow"
                        textSize="xs"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="green"
                        add="dot"
                        textColor="green"
                        textSize="xs"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="blue"
                        add="dot"
                        textColor="blue"
                        textSize="xs"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="indigo"
                        add="dot"
                        textColor="indigo"
                        textSize="xs"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="purple"
                        add="dot"
                        textColor="purple"
                        textSize="xs"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        text="Badge"
                        badgeColor="pink"
                        add="dot"
                        textColor="pink"
                        textSize="xs"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Flat With Remove Button">
                    <Badge
                        type="flat"
                        add="button"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        type="flat"
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        type="flat"
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        type="flat"
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        type="flat"
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        type="flat"
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        type="flat"
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Flat Pill With Remove Button">
                    <Badge
                        shape="pill"
                        type="flat"
                        add="button"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
            </List>
            <List>
                <ListContent title="Small With Border">
                    <Badge small={true} text="Badge" textSize="xs" />
                    <Badge
                        small={true}
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        small={true}
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        small={true}
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        small={true}
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        small={true}
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        small={true}
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        small={true}
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="Small Flat">
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="Small Pill With Border">
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="Small Flat Pill">
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="red"
                        textColor="red"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="yellow"
                        textColor="yellow"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="green"
                        textColor="green"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="blue"
                        textColor="blue"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="indigo"
                        textColor="indigo"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="purple"
                        textColor="purple"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="pink"
                        textColor="pink"
                        textSize="xs"
                    />
                </ListContent>
                <ListContent title="Small With Border And Dot">
                    <Badge
                        small={true}
                        badgeColor="red"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        small={true}
                        badgeColor="yellow"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        small={true}
                        badgeColor="green"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        small={true}
                        badgeColor="blue"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        small={true}
                        badgeColor="indigo"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        small={true}
                        badgeColor="purple"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        small={true}
                        badgeColor="pink"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Small Pill With Border And Dot">
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="red"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="yellow"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="green"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="blue"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="indigo"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="purple"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="pink"
                        add="dot"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Small Flat With Dot">
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        add="dot"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="red"
                        add="dot"
                        textColor="red"
                        textSize="xs"
                        addedColor="red"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="yellow"
                        add="dot"
                        textColor="yellow"
                        textSize="xs"
                        addedColor="yellow"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="green"
                        add="dot"
                        textColor="green"
                        textSize="xs"
                        addedColor="green"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="blue"
                        add="dot"
                        textColor="blue"
                        textSize="xs"
                        addedColor="blue"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="indigo"
                        add="dot"
                        textColor="indigo"
                        textSize="xs"
                        addedColor="indigo"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="purple"
                        add="dot"
                        textColor="purple"
                        textSize="xs"
                        addedColor="purple"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="pink"
                        add="dot"
                        textColor="pink"
                        textSize="xs"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Small Flat Pill With Dot">
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        add="dot"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="red"
                        add="dot"
                        textColor="red"
                        textSize="xs"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="yellow"
                        add="dot"
                        textColor="yellow"
                        textSize="xs"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="green"
                        add="dot"
                        textColor="green"
                        textSize="xs"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="blue"
                        add="dot"
                        textColor="blue"
                        textSize="xs"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="indigo"
                        add="dot"
                        textColor="indigo"
                        textSize="xs"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="purple"
                        add="dot"
                        textColor="purple"
                        textSize="xs"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        text="Badge"
                        badgeColor="pink"
                        add="dot"
                        textColor="pink"
                        textSize="xs"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Small With Border And Remove Button">
                    <Badge
                        small={true}
                        add="button"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        small={true}
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        small={true}
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        small={true}
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        small={true}
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        small={true}
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        small={true}
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        small={true}
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Small Pill With Border And Remove Button">
                    <Badge
                        shape="pill"
                        small={true}
                        add="button"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        small={true}
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Small Flat With Remove Button">
                    <Badge
                        type="flat"
                        small={true}
                        add="button"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        type="flat"
                        small={true}
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
                <ListContent title="Small Flat Pill With Remove Button">
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        add="button"
                        text="Badge"
                        textSize="xs"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        badgeColor="red"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="red"
                        addedColor="red"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        badgeColor="yellow"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="yellow"
                        addedColor="yellow"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        badgeColor="green"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="green"
                        addedColor="green"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        badgeColor="blue"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="blue"
                        addedColor="blue"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        badgeColor="indigo"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="indigo"
                        addedColor="indigo"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        badgeColor="purple"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="purple"
                        addedColor="purple"
                    />
                    <Badge
                        shape="pill"
                        type="flat"
                        small={true}
                        badgeColor="pink"
                        add="button"
                        text="Badge"
                        textSize="xs"
                        textColor="pink"
                        addedColor="pink"
                    />
                </ListContent>
            </List>
        </div>
    )
}

export default Badges
