import React from 'react'
import List from 'src/shared/layout/list/List.tsx'
import ListContent from 'src/shared/layout/list/ListContent.tsx'
import Avatar from 'src/features/avatars/components/Avatar.tsx'
import GroupAvatar from 'src/features/avatars/components/GroupAvatar.tsx'

const Avatars = () => {
    return (
        <div className="flex min-h-screen w-full items-center justify-center">
            <List>
                <ListContent title="Circular Avatars">
                    <Avatar
                        shape="circular"
                        size={6}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="circular"
                        size={10}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="circular"
                        size={12}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="circular"
                        size={14}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                </ListContent>
                <ListContent title="Rounded Avatars">
                    <Avatar
                        shape="rounded"
                        size={6}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="rounded"
                        size={10}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="rounded"
                        size={12}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                    <Avatar
                        shape="rounded"
                        size={10}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    />
                </ListContent>
                <ListContent title="Circular Avatars With Top Notification">
                    <Avatar
                        shape="circular"
                        size={6}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={1.5}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={10}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={2.5}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={12}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={3}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={14}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={3.5}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={16}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={4}
                        locate="top"
                    />
                </ListContent>
                <ListContent title="Rounded Avatars With Top Notification">
                    <Avatar
                        shape="rounded"
                        size={6}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={1.5}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={10}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={2.5}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={12}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={3}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={14}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={3.5}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={16}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={4}
                        locate="top"
                    />
                </ListContent>
                <ListContent title="Circular Avatars With Bottom Notification">
                    <Avatar
                        shape="circular"
                        size={6}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={1.5}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={10}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={2.5}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={12}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={3}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={14}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={3.5}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={16}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={4}
                        locate="bottom"
                    />
                </ListContent>
                <ListContent title="Rounded Avatars With Bottom Notification">
                    <Avatar
                        shape="rounded"
                        size={6}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={1.5}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={10}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={2.5}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={12}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="offline"
                        statusSize={3}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={14}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="disable"
                        statusSize={3.5}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={16}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        status="online"
                        statusSize={4}
                        locate="bottom"
                    />
                </ListContent>
                <ListContent title="Circular Avatars With Placeholder Icon">
                    <Avatar
                        shape="circular"
                        size={6}
                        type="icon"
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="icon"
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                    />
                    <Avatar
                        shape="circular"
                        size={10}
                        type="icon"
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                    />
                    <Avatar
                        shape="circular"
                        size={12}
                        type="icon"
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                    />
                    <Avatar
                        shape="circular"
                        size={14}
                        type="icon"
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                    />
                </ListContent>
                <ListContent title="Circular Avatars With Placeholder Initials">
                    <Avatar
                        shape="circular"
                        size={6}
                        type="initial"
                        text="TW"
                        textSize="xs"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="initial"
                        text="TW"
                        textSize="sm"
                    />
                    <Avatar
                        shape="circular"
                        size={10}
                        type="initial"
                        text="TW"
                        textSize="lg"
                    />
                    <Avatar
                        shape="circular"
                        size={12}
                        type="initial"
                        text="TW"
                        textSize="lg"
                    />
                    <Avatar
                        shape="circular"
                        size={14}
                        type="initial"
                        text="TW"
                        textSize="xl"
                    />
                </ListContent>
            </List>
            <List>
                <ListContent title="Avatar Group Stacked Bottom To Top">
                    <GroupAvatar>
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                    </GroupAvatar>
                    <GroupAvatar space={2}>
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                    </GroupAvatar>
                    <GroupAvatar space={2}>
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                    </GroupAvatar>
                </ListContent>
                <ListContent title="Avatar Group Stacked Top To Bottom">
                    <GroupAvatar to="bottom">
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={6}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                    </GroupAvatar>
                    <GroupAvatar space={2} to="bottom">
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={8}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                    </GroupAvatar>
                    <GroupAvatar space={2} to="bottom">
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                    </GroupAvatar>
                </ListContent>
                <ListContent title="With Text">
                    <Avatar
                        shape="circular"
                        size={9}
                        type="img"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        caption="H.S Kim"
                        captionSize="sm"
                        subCaption="View Website"
                        subCaptionSize="xs"
                        href="https://hskim.me"
                    />
                </ListContent>
                <ListContent title="Basic Icon Single Avatar">
                    <Avatar
                        shape="circular"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                        status="offline"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                        status="disable"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                        status="online"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                        status="offline"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                        status="disable"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                        status="online"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        type="icon"
                        status="online"
                        statusSize={2}
                        locate="bottom"
                        caption="Icon"
                        captionSize="sm"
                        subCaption="test"
                        subCaptionSize="xs"
                        href="https://hskim.me"
                    />
                </ListContent>
                <ListContent title="Basic Initial Single Avatar">
                    <Avatar
                        shape="circular"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                        status="offline"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                        status="disable"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                        status="online"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                        status="offline"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                        status="disable"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                        status="online"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        type="initial"
                        text="HS"
                        textSize="base"
                        status="offline"
                        statusSize={2}
                        locate="top"
                        caption="Initial"
                        captionSize="sm"
                        subCaption="test"
                        subCaptionSize="xs"
                        href="https://hskim.me"
                    />
                </ListContent>
                <ListContent title="Basic Image Single Avatar">
                    <Avatar
                        shape="circular"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                        status="offline"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                        status="disable"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                        status="online"
                        statusSize={2}
                        locate="bottom"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                        status="offline"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                        status="disable"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="rounded"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                        status="online"
                        statusSize={2}
                        locate="top"
                    />
                    <Avatar
                        shape="circular"
                        size={8}
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        type="img"
                        status="disable"
                        statusSize={2}
                        locate="bottom"
                        caption="Image"
                        captionSize="sm"
                        subCaption="test"
                        subCaptionSize="xs"
                        href="https://hskim.me"
                    />
                </ListContent>
                <ListContent title="Grouped Icon Avatars">
                    <GroupAvatar to="top" space={2}>
                        <Avatar
                            shape="circular"
                            size={10}
                            type="icon"
                            src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        />
                        <Avatar
                            shape="rounded"
                            size={10}
                            type="icon"
                            src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="icon"
                            src="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"
                            status="offline"
                            statusSize={3}
                            locate="bottom"
                        />
                    </GroupAvatar>
                </ListContent>
                <ListContent title="Grouped Initial Avatars">
                    <GroupAvatar>
                        <Avatar
                            shape="rounded"
                            size={10}
                            type="initial"
                            text="TW"
                            textSize="lg"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="initial"
                            text="TW"
                            textSize="lg"
                        />
                        <Avatar
                            shape="rounded"
                            size={10}
                            type="initial"
                            text="TW"
                            textSize="lg"
                            status="online"
                            statusSize={3}
                            locate="top"
                        />
                    </GroupAvatar>
                </ListContent>
                <ListContent title="Grouped Image Avatars">
                    <GroupAvatar>
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="rounded"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        />
                        <Avatar
                            shape="circular"
                            size={10}
                            type="img"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                            status="disable"
                            statusSize={3}
                            locate="bottom"
                        />
                    </GroupAvatar>
                </ListContent>
            </List>
        </div>
    )
}

export default Avatars
